/**
 * Seed Payload CMS (SQLite) from the Menurio snapshot in ./menu.json
 * (generated by /data/generate.mjs — same source as the Vision frontend).
 *
 * Run:
 *   cp .env.example .env
 *   npm install
 *   npm run dev   (once, to initialise the DB)
 *   npm run seed
 *
 * Creates/updates (idempotent on menurioId):
 *   menu-sections (14) -> categories -> menu-items (512), EL + EN
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { getPayload } from 'payload';
import config from '../../payload.config.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

type Localized = { el: string; en: string };
interface SeedItem { id: number; active?: boolean; name: Localized; description: Localized; price: string; image: string }
interface SeedCat { id: number; active?: boolean; name: Localized; description: Localized; image: string; notes: { el: string; en: string }[]; items: SeedItem[] }
interface SeedSection { id: number; order: number; slug: string; image: string; name: Localized; description: Localized; categories: SeedCat[] }

async function upsert(payload: Awaited<ReturnType<typeof getPayload>>, collection: string, whereVal: unknown, data: Record<string, unknown>) {
  const found = await payload.find({ collection: collection as never, where: { menurioId: { equals: whereVal } } as never, limit: 1 });
  const existing = (found.docs as Record<string, unknown>[])[0];
  if (existing) {
    await payload.update({ collection: collection as never, id: existing.id as string, data: data as never });
    return existing.id as string;
  }
  const created = await payload.create({ collection: collection as never, data: data as never });
  return (created as Record<string, unknown>).id as string;
}

async function main() {
  const payload = await getPayload({ config });
  const raw = JSON.parse(fs.readFileSync(path.join(__dirname, 'menu.json'), 'utf8')) as { sections: SeedSection[] };
  console.log(`Seeding ${raw.sections.length} sections…`);

  try {
    const users = await payload.find({ collection: 'users', limit: 1 });
    if (users.totalDocs === 0) {
      await payload.create({
        collection: 'users',
        data: { email: 'admin@kazanoba.local', password: 'kazanoba-vision-123', name: 'Kazanoba Admin', role: 'admin' }
      });
      console.log('Created dev admin: admin@kazanoba.local / kazanoba-vision-123');
    }
  } catch (e) {
    console.warn('Skipping user seed (run dev once first):', (e as Error).message);
  }

  let catCount = 0;
  let itemCount = 0;

  for (const s of [...raw.sections].sort((a, b) => a.order - b.order)) {
    const sectionId = await upsert(payload, 'menu-sections', s.id, {
      menurioId: s.id,
      slug: s.slug || `s-${s.id}`,
      order: s.order,
      active: true,
      image: s.image,
      name: s.name.el,
      description: s.description.el
    });
    await payload.update({ collection: 'menu-sections', id: sectionId, data: { name: s.name.en, description: s.description.en } as never, locale: 'en' });

    for (const [ci, c] of s.categories.entries()) {
      const categoryId = await upsert(payload, 'categories', c.id, {
        menurioId: c.id,
        slug: `c-${c.id}`,
        section: sectionId,
        order: ci,
        active: c.active !== false,
        image: c.image,
        name: c.name.el,
        description: c.description.el,
        notes: c.notes.map((n: { el: string }) => ({ text: n.el }))
      });
      await payload.update({
        collection: 'categories',
        id: categoryId,
        data: { name: c.name.en, description: c.description.en, notes: c.notes.map((n: { en: string }) => ({ text: n.en })) } as never,
        locale: 'en'
      });
      catCount++;

      for (const [ii, it] of c.items.entries()) {
        const itemId = await upsert(payload, 'menu-items', it.id, {
          menurioId: it.id,
          slug: `i-${it.id}`,
          section: sectionId,
          category: categoryId,
          order: ii,
          active: it.active !== false,
          price: it.price,
          image: it.image,
          name: it.name.el,
          description: it.description.el
        });
        await payload.update({
          collection: 'menu-items',
          id: itemId,
          data: { name: it.name.en, description: it.description.en } as never,
          locale: 'en'
        });
        itemCount++;
      }
    }
  }

  console.log(`Done. sections=${raw.sections.length} categories=${catCount} items=${itemCount}`);
  process.exit(0);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
